### ISSUE TITLE
[Solution] local_moves

### ISSUE THREAD

**Issue by lutzzdias** [lutzzdias/travelling-salesman-problem#12]
Returns an iterable with all of the possible moves for the current solution state.

In our case, a move would probably be created with the [3 opt](http://tsp-basics.blogspot.com/2017/03/3-opt-move.html) logic but this is open for debate

**Comment by AlexandreAndrade00** [comment]
A move will be created with the last case of 3-opt. Because it isn't necessary to reverse the segments, in consequence, only the new edge distances change and that's what we want.

[3-opt_7-case.pdf](https://github.com/lutzzdias/travelling-salesman-problem/files/13513818/Alexandre.pdf)


@lutzzdias
